lag_admin:
    admins:
        article:
            entity: App\Entity\Article
            form: App\Form\Type\ArticleType
            controller: JKCmsBundle:Article
            actions:
                list:
                    title: cms.article.list
                    order:
                        id: desc
                    fields:
                        id: ~
                        title:
                            type: link
                            options:
                                length: 40
                                route: cms.article.edit
                                parameters: {id: ~}
                        category: ~
                        author: ~
                        publicationStatus:
                            type: mapped
                            options:
                                map:
                                    0: cms.publication.draft
                                    1: cms.publication.validation
                                    2: cms.publication.published
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        updatedAt: {type: date, options: {format: d/m/Y}}
                        _actions:
                            type: action_collection
                            options:
                                fields:
                                    _edit:
                                        type: action
                                        options:
                                            title: cms.menu.edit
                                            route: cms.article.edit
                                            parameters: {id: ~}
                                            icon: pencil
                                    _delete:
                                        type: action
                                        options:
                                            title: cms.menu.delete
                                            route: cms.article.delete
                                            parameters: {id: ~}
                                            icon: remove
                create: ~
                edit:
                    menus:
                        top:
                            items:
                                preview:
                                    text: cms.article.preview
                                    route: lecomptoir.article.preview
                                    parameters: {id: ~}
                                    icon: fa fa-eye
                                    attr:
                                        target: _blank

                delete: ~
