lag_admin:
    admins:
        category:
            entity: App\Entity\Category
            form: App\Form\Type\CategoryType
            actions:
                batch: ~
                create: ~
                edit: ~
                delete: ~
                list:
                    title: cms.category.list
                    menus:
                        top:
                            items:
                                create:
                                    admin: category
                                    action: create
                                    icon: fa fa-plus
                    fields:
                        id: ~
                        name:
                            type: link
                            options:
                                route: cms.category.edit
                                parameters: {id: ~}
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        articles:
                            type: count
                        displayInHomepage:
                            type: boolean
                        _actions:
                            type: collection
                            options:
                                _edit:
                                    type: action
                                    options:
                                        title: cms.menu.edit
                                        route: cms.category.edit
                                        parameters: {id: ~}
                                        icon: pencil
                                _delete:
                                    type: action
                                    options:
                                        title: cms.menu.delete
                                        route: cms.category.delete
                                        parameters: {id: ~}
                                        icon: remove
                    order:
                        updatedAt: desc
