lag_admin:
    admins:
        media:
            controller: JKCmsBundle:Media
            entity: App\Entity\Media
            form: App\Form\Type\MediaType
            actions:
                list:
                    pager: false
                    order:
                        updatedAt: desc
                edit:
                create:
                delete:
