services:
    # Upload
    cms.upload.jquery_upload_type:
        class: JK\CmsBundle\Form\Type\JQueryUploadType
        arguments:
            - '@oneup_uploader.templating.uploader_helper'
            - '@cms.media.media_upload_transformer'
        tags:
            - {name: form.type}

    # Media
    cms.media.media_type:
        class: JK\CmsBundle\Form\Type\MediaType
        arguments:
            - '@cms.media.media_transformer'
        tags:
            - {name: form.type}

    # Comment
    cms.comment.recaptcha_validator:
        class: JK\CmsBundle\Form\Validator\RecaptchaValidator
        arguments:
            - '%google_recaptcha_secret%'
            - '@request_stack'
        tags:
            - {name: validator.constraint_validator}

    cms.comment.add_comment_type:
        class: JK\CmsBundle\Form\Type\AddCommentType
        autowire: true
        tags:
            - {name: form.type}

    # Recaptcha
    cms.recaptcha.recaptcha_type:
        class: JK\CmsBundle\Form\Type\RecaptchaType
        arguments:
            - '%google_recaptcha_site_key%'
        tags:
            - {name: form.type}

    cms.tag.embed_collection_type:
        class: JK\CmsBundle\Form\Type\TagCollectionEmbedType
        arguments:
            - '@cms.tag.collection_transformer'
        tags:
            - {name: form.type}

    # Form extensions
    cms.form.assets_extension:
        class: JK\CmsBundle\Form\Extension\AssetsExtension
        autowire: true
        tags:
            - {name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType}

    cms.search.form_handler:
        class: JK\CmsBundle\Form\Handler\SearchFormHandler
        autowire: true

    # Page
    cms.page.page_type:
        class: JK\CmsBundle\Form\Type\PageType
        tags:
            - {name: form.type, alias: page}
        arguments:
            - '@cms.form.helper'
