services:
#    jk_cms.example:
#        class: JK\CmsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    cms.article.subscriber:
        class: JK\CmsBundle\Event\Subscriber\ArticleSubscriber
        tags:
            - {name: doctrine.event_subscriber}
        arguments:
            - '@router'
