parameters:
    cms.media.class: JK\CmsBundle\Entity\Media

services:
    cms.article.subscriber:
        class: JK\CmsBundle\Event\Subscriber\ArticleSubscriber
        arguments:
            - '@router'
        tags:
            - {name: doctrine.event_subscriber}

    cms.upload.subscriber:
        class: JK\CmsBundle\Event\Subscriber\UploadSubscriber
        arguments:
            - '@cms.media.media_repository'
            - '@cms.assets.helper'
        tags:
            - {name: kernel.event_subscriber}

    cms.media.media_repository:
        class: JK\CmsBundle\Repository\MediaRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - JK\CmsBundle\Entity\Media

    cms.twig.cms_extension:
        class: JK\CmsBundle\Twig\CmsExtension
        autowire: true
        tags:
            - {name: twig.extension}

    cms.assets.helper:
        class: JK\CmsBundle\Assets\AssetsHelper
        arguments:
            - '%kernel.environment%'
            - '%cms.assets.mapping%'
            - '@router'
            - '@liip_imagine.cache.manager'
            - '%kernel.root_dir%'

    cms.article.repository:
        class: JK\CmsBundle\Repository\ArticleRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - JK\CmsBundle\Entity\Article

    cms.comment.comment_mailer:
        class: JK\CmsBundle\Mail\CommentMailer
        arguments:
            - '@swiftmailer.mailer'
            - '@jk.cms.comment_repository'
            - '@twig'
            - '%squirrel_mail%'
