framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    csrf_protection: true
    http_method_override: true

    session:
        handler_id: ~

    esi: false
    fragments: true
    php_errors:
        log: true

    cache:
        prefix_seed: johnkrovitch/lecomptoirdelecureil

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
