liip_imagine:
    driver: gd
#    loaders:
#        default:
#            filesystem:
#                data_root: '%liip_imagine_filesystem_root%'
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        media_thumbnail:
            quality: 75
            filters:
                thumbnail: {size: [120, 90], mode: outbound}
        media_gallery:
            filters:
                thumbnail: {size: [200, 250], mode: outbound}
        article_thumbnail:
            filters:
                thumbnail: {size: [200, 300], mode: outbound}
        article_content:
            filters:
                thumbnail: {size: [200, 250], mode: outbound}
        category_thumbnail:
            filters:
                thumbnail: {size: [200, 300], mode: outbound}
        category_big:
            filters:
                thumbnail: {size: [439, 305], mode: outbound}
        raw: ~
