security:
    encoders:
        App\Entity\User: sha512

    providers:
        App\Service\Guard\UserProvider\GoogleUserProvider:
            id: App\Service\Guard\UserProvider\GoogleUserProvider

    role_hierarchy:
        ROLE_OAUTH_USER:  ROLE_ADMIN
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - {path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/connect/google, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/cms, role: ROLE_ADMIN}
        - {path: ^/article/, role: ROLE_ADMIN}
        - {path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path: /cms/logout
            oauth:
                resource_owners:
                    google:   /login/check-google
                login_path:   /login
                failure_path: /login
                default_target_path: /cms/dashboard
                use_forward:  false
                oauth_user_provider:
                    service: App\Service\Guard\UserProvider\GoogleUserProvider
