language: php

php:
    - 5.5.9
    - 5.6
    - 7.0

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mysql -e "create database IF NOT EXISTS symfony;"
    - mysql -e "create database IF NOT EXISTS symfony_test;"
    - cp app/config/parameters.yml.dist app/config/parameters.yml

install:
    - composer update
    - bin/console doctrine:database:create -n --if-not-exists --env=test
    - bin/console doctrine:schema:update -n -f --env=test
    - bin/console doctrine:fixtures:load --append -v --env=test
    - bin/console cache:clear --env=test

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover -c app

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
