language: php

services:
    - mysql

php:
    - 7.2

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - make tests@database

install:
    - composer install --dev
    - make tests

script:
  - bin/phpunit --coverage-text --coverage-clover=coverage.clover -c app

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
