language: php

php:
    - 7.0

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mysql -e "create database IF NOT EXISTS symfony;"
    - mysql -e "create database IF NOT EXISTS symfony_test;"
    - cp app/config/parameters.yml.dist app/config/parameters.yml

install:
    - make update
    - make tests

script:
  - bin/phpunit --coverage-text --coverage-clover=coverage.clover -c app

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
