language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_install:
    - mysql -e "create database IF NOT EXISTS symfony;"
    - cp app/config/parameters.yml.dist app/config/parameters.yml

install:
    - composer install
    - bin/console doctrine:fixtures:load -n

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover -c app

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
