lag_admin:
    admins:
        article:
            entity: JK\CmsBundle\Entity\Article
            form: BlueBear\CmsBundle\Form\Type\ArticleType
            actions:
                list:
                    title: cms.article.list
                    filters:
                        title: ~
                        publicationStatus:
                            type: choice
                            options:
                                choices:
                                    cms.publication.draft: 0
                                    cms.publication.waiting_validation: 1
                                    cms.publication.published: 2
                                placeholder: cms.search.by_publication_status
                        category:
                            type: entity
                            options:
                                class: BlueBear\CmsBundle\Entity\Category
                                placeholder: cms.search.by_category
                    order:
                        id: desc
                    menus:
                        top:
                            items:
                                create:
                                    admin: article
                                    action: create
                                    icon: fa fa-plus
                    fields:
                        id: ~
                        title:
                            type: link
                            options:
                                length: 40
                                route: cms.article.edit
                                parameters: {id: ~}
                        category: ~
                        author: ~
                        publicationStatus:
                            type: mapped
                            options:
                                mapping:
                                    0: cms.publication.draft
                                    1: cms.publication.waiting_validation
                                    2: cms.publication.published
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        updatedAt: {type: date, options: {format: d/m/Y}}
                        _actions: ~
                create: ~
                edit:
                    template: '@JKCms/Article/edit.html.twig'
                    menus:
                        top:
                            items:
                                preview:
                                    text: cms.article.preview
                                    route: lecomptoir.article.preview
                                    parameters: {id: ~}
                                    icon: fa fa-eye
                                    attr:
                                        target: _blank
                delete: ~
