lag_admin:
    admins:
        comment:
            entity: BlueBear\CmsBundle\Entity\Comment
            form: BlueBear\CmsBundle\Form\Type\CommentType
            actions:
                list:
                    title: cms.comment.list
                    fields:
                        id: ~
                        content: {type: string, options: {length: 150}}
                        article: ~
                        createdAt: {type: date, options: {format: 'd/m/Y à h:i'}}
                        updatedAt: {type: date, options: {format: 'd/m/Y à h:i'}}
                        _actions: ~
                    # Comments creations through backoffice is not allowed
                    menus: false
                    order:
                        updatedAt: desc
                create: ~
                edit: ~
                delete: ~
