lag_admin:
    admins:
        media:
            controller: JKCmsBundle:Media
            entity: JK\CmsBundle\Entity\Media
            form: JK\CmsBundle\Form\Type\MediaType
            actions:
                list:
                    pager: false
                    order:
                        updatedAt: desc
                    route_defaults:
                        _controller: JKCmsBundle:Media:list
                edit:
                create: ~
                delete: ~
