cms.media.add_gallery_modal:
    path: /cms/media/gallery/modal
    defaults: {_controller: JKCmsBundle:Media:modalGallery}

cms.media.gallery.content:
    path: /cms/media/gallery/content
    defaults: {_controller: JKCmsBundle:Media:galleryContent}

cms.media.tinymce.insert_image:
    path: /cms/media/tinymce/insert-media/{ids}
    defaults: {_controller: JK\CmsBundle\Action\TinyMce\InsertImage}

cms.media.tinymce.edit_image:
    path: /cms/media/tinymce/edit-media
    defaults: {_controller: JK\CmsBundle\Action\TinyMce\EditMedia}

cms.dashboard.go_to_new_comments:
    path: /cms/dashboard/new-comments
    defaults: {_controller: JKCmsBundle:Dashboard:goToNewComments}

cms.dashboard:
    path: /cms/dashboard
    defaults: {_controller: JKCmsBundle:Dashboard:dashboard}

cms.module.render:
    path: /cms/modules/render/{zone}
    defaults: {_controller: JKCmsBundle:Module:render}

cms.search:
    path: /search
    defaults: {_controller: JKCmsBundle:Search:search}

cms.media.gallery.ajax:
    path: /cm/media/gallery/ajax
    defaults: {_controller: JK\CmsBundle\Action\Media\Gallery}
