lecomptoir.homepage:
    path:     /
    defaults: {_controller: App:Main:index}

lecomptoir.contact:
    path: /contact
    defaults: {_controller: App:Main:contact}

lecomptoir.about:
    path: /a-propos
    defaults: {_controller: App:Main:whoAmI}

lecomptoir.legal:
    path: /mentions-legales
    defaults: {_controller: App:Main:legal}

# Partners pages
lecomptoir.partner:
    path: /partenaires/{partnerSlug}
    defaults: {_controller: App:Main:partner}

# Articles Pages
lecomptoir.article.list_by_category:
    path: /category/{categorySlug}
    defaults: {_controller: App:Article:filter}

lecomptoir.article.list_by_tag:
    path: /tag/{tagSlug}
    defaults: {_controller: App:Article:filter}

lecomptoir.article.unsubscribe:
    path: /{slug}/{email}/unsubscribe
    defaults: {_controller: App:Article:unsubscribe}

# Article preview
lecomptoir.article.preview:
    path: /article/{id}/preview
    defaults: {_controller: App:Article:preview}

#lecomptoir.article.show:
#    path:  /{year}/{month}/{slug}
#    defaults: {_controller: App:Article:show}

# fix for bad wordpress urls
lecomptoir.article.show2:
    path:  /{year}/{month}/{slug}/
    defaults: {_controller: App:Article:show}

### RSS ###
lecomptoir.feed:
    path: /feed
    defaults: {_controller: App:Main:feed}
###########

# Sitemap
lecomptoir.sitemap:
    path: /sitemap.xml
    defaults: {_controller: App:Main:sitemap}

# Free Pages
#lecomptoir.free_pages:
#    path: /{pageSlug}
#    defaults: {_controller: App:Page:show}
