jk_assets:
    debug: false
    register_assets: true
    filters:
        compass:
            bin: /usr/local/bin/compass
        merge: ~
        minify: ~
        copy: ~
    tasks:
        main.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - app/Resources/assets/sass/main.scss
                - vendor/components/bootstrap/css/bootstrap.min.css
                - vendor/components/bootstrap/css/bootstrap-theme.min.css
                - vendor/components/font-awesome/css/font-awesome.min.css
                - app/Resources/assets/css/hover-min.css
            destinations:
                - web/css/main.css

        fonts:
            filters: ~
            sources:
                - vendor/components/bootstrap/fonts/
                - vendor/components/font-awesome/fonts/
            destinations:
                - web/fonts/

        cms.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - src/BlueBear/CmsBundle/Resources/scss/cms.scss
            destinations:
                - src/BlueBear/CmsBundle/Resources/public/css/cms.css

        cms.js:
            filters:
                - merge
                - minify
            sources:
                - src/JK/CmsBundle/Resources/assets/js/jquery.iframe-transport.js
                - src/JK/CmsBundle/Resources/assets/js/cms/fileupload.js
                - vendor/blueimp/jquery-file-upload/js/jquery.fileupload.js
            destinations:
                - src/JK/CmsBundle/Resources/public/js/cms.js

        tinymce.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - src/JK/CmsBundle/Resources/assets/sass/tinymce.scss
                - web/css/main.css
            destinations:
                - src/JK/CmsBundle/Resources/public/css/tinymce.css
