jk_assets:
    debug: false
    register_assets: true
    filters:
        compass:
            bin: compass
        merge: ~
        minify: ~
        copy: ~
    tasks:
        # App
        app.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - app/Resources/assets/sass/main.scss
                - app/Resources/assets/css/hover-min.css
                - vendor/components/bootstrap/css/bootstrap.min.css
                - vendor/components/font-awesome/css/font-awesome.min.css
            destinations:
                - web/css/main.css

        app.js:
            filters:
                - minify
                - merge
            sources:
                - vendor/components/jquery/jquery.min.js
                - vendor/components/bootstrap/js/bootstrap.min.js
            destinations:
                - web/js/app.js
        fonts:
            filters: ~
            sources:
                - vendor/components/bootstrap/fonts/
                - vendor/components/font-awesome/fonts/
            destinations:
                - web/fonts/

        # CMS
        cms.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - src/JK/CmsBundle/Resources/assets/scss/cms.scss
                - vendor/components/bootstrap/css/bootstrap.min.css
                - vendor/lag/adminbundle/LAG/AdminBundle/Resources/public/scss/admin.scss
                - vendor/components/font-awesome/css/font-awesome.min.css
            destinations:
                - web/css/cms.css

        cms.tinymce.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - src/JK/CmsBundle/Resources/assets/scss/tinymce.scss
            destinations:
                - web/css/cms.tinymce.css

        cms.js:
            filters:
                - minify
                - merge
            sources:
                - vendor/components/jquery/jquery.min.js
                - vendor/components/jqueryui/jquery-ui.min.js
                - vendor/components/bootstrap/js/bootstrap.min.js
                - src/JK/CmsBundle/Resources/assets/js
                - vendor/blueimp/jquery-file-upload/js/jquery.fileupload.js
            destinations:
                - web/js/cms.js

        tinymce:
            filters: ~
            sources:
                - vendor/tinymce/tinymce
            destinations:
                - web/js/tinymce
