imports:
    - { resource: admin/category.yml }
    - { resource: admin/article.yml }
    - { resource: admin/comment.yml }
    - { resource: admin/media.yml }
    - { resource: admin/tag.yml }
    - { resource: admin/page.yml }

blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~

#stfalcon_tinymce:
#    include_jquery: false
#    tinymce_jquery: false
#    external_plugins:
#        imagetools:
#            url: 'asset[bundles/bluebearcms/js/tinymce/plugins/imagetools/plugin.js]'
#    theme:
#        simple:
#            theme: "modern"
#        advanced:
#             theme: "modern"
#             plugins:
#                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
#                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
#                 - "insertdatetime media nonbreaking save table contextmenu directionality"
#                 - "emoticons template paste textcolor"
#             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#             toolbar2: "print preview media | forecolor backcolor emoticons | imagetools"
#             image_advtab: true
#             menubar: true
#             imagetools_toolbar: "imageoptions"


# app/config/config.yml
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: 'LAGAdminBundle:Menu:bootstrap_menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

lag_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derrière les noisettes
        description: Des noisettes et des livres
        bootstrap: true
        base_template: 'BlueBearCmsBundle::layout.html.twig'
        max_per_page: 25
        routing:
            name_pattern: cms.{admin}.{action}
            # CmsBundle already have "cms" prefix
            url_pattern:  /{admin}/{action}
        date_format: '\L\e d/m/Y à h:i:s'
        translation:
            enabled: true
            pattern: cms.{admin}.{key}

    menus:
        main:
            items:
                category:
                    admin: category
                    icon: fa fa-folder-open
                article:
                    admin: article
                    icon: fa fa-newspaper-o
                tag:
                    admin: tag
                    icon: fa fa-tags
                media:
                    admin: media
                    icon: fa fa-image
                comment:
                    admin: comment
                    icon: fa fa-comment
                page:
                    admin: page
                    icon: fa fa-code
                partners:
                    admin: partner
                    icon: fa fa-book
                    text: lecomptoir.partner.list
                parameters:
                    url: '#'
                    text: Parameters
                    icon: fa fa-gear
                    items:
                        imports:
                            admin: import
                            action: list
                            icon: fa fa-upload
                logout:
                    route: logout
                    icon: fa fa-sign-out

    # Admins configurations
    admins:
        ### User ###
        user:
            entity: BlueBear\CmsBundle\Entity\User
            form: BlueBear\CmsBundle\Form\Type\UserType
            actions:
                list:
                    fields:
                        id: ~
                        username: ~
                        email: ~
                        enabled: ~
                        _actions: ~
                create: ~
                edit: ~
                delete: ~

        parameters:
            entity: BlueBear\CmsBundle\Entity\Parameters
            form: BlueBear\CmsBundle\Form\Type\ParametersType
            actions:
                list: ~
                create: ~
                edit: ~
                delete: ~

        import:
            entity: BlueBear\CmsBundle\Entity\Import
            form: BlueBear\CmsBundle\Form\Type\ImportType
            controller: 'BlueBearCmsBundle:Import'
            actions:
                list:
                    menus:
                        top:
                            items:
                                import:
                                    admin: import
                                    action: create
                                    icon: fa fa-upload
                    fields:
                        id: ~
                        label: {type: string, options: {length: 100}}
                        comments: {type: string, options: {length: 100}}
                        status: ~
                create: ~
                edit: ~
                delete: ~
        partner:
            entity: AppBundle\Entity\Partner
            form: AppBundle\Form\Type\PartnerType
            actions: ~

bluebear_media: ~

# rss/atom feed bundle
eko_feed:
    feeds:
        article:
            title: Le Comptoir de L'Ecureuil - Articles
            description: Voici les articles du comptoir de l'écureuil
            link:
                route_name: lecomptoir.feed
            encoding: utf-8

oneup_uploader:
    mappings:
        media_gallery:
            frontend: blueimp
            storage:
                directory: '%kernel.root_dir%/../web/uploads/gallery'
        article_thumbnail:
            frontend: blueimp
            storage:
                directory: '%kernel.root_dir%/../web/uploads/articles/thumbnails'
        category_thumbnail:
            frontend: blueimp
            storage:
                directory: '%kernel.root_dir%/../web/uploads/categories/thumbnails'

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: '%liip_imagine_bundle_root%'
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        media_thumbnail:
            quality: 75
            filters:
                thumbnail: {size: [120, 90], mode: outbound}
        media_gallery:
            filters:
                thumbnail: {size: [200, 250], mode: outbound}
        article_thumbnail:
            filters:
                thumbnail: {size: [200, 300], mode: outbound}
        category_thumbnail:
            filters:
                thumbnail: {size: [200, 300], mode: outbound}
        category_big:
            filters:
                thumbnail: {size: [439, 305], mode: outbound}

jk_cms:
    assets: ~

jk_database:
    backup_directory: '%backup_directory%'

dunglas_action:
    directories:
        - '../src/JK/CmsBundle/Action/*'
