blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~


lag_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derrière les noisettes
        description: Des noisettes et des livres
        bootstrap: true
        layout: BlueBearCmsBundle::layout.html.twig
        routing:
            name_pattern: bluebear.cms.{admin}.{action}
            url_pattern:  /{admin}/{action}
        date_format: d/m/Y h:i:s
        translation:
            pattern: lecomptoir.{key}
    admins:
        user:
            entity: BlueBear\CmsUserBundle\Entity\User
            form: user
            actions:
                list:
                    fields:
                        id: ~
                        username: ~
                        email: ~
                        enabled: ~
                        _actions: ~
                create: ~
                edit: ~
                delete: ~

        category:
            entity: BlueBear\CmsBundle\Entity\Category
            form: category
            actions:
                create: ~
                edit: ~
                delete: ~
                list:
                    title: bluebear.cms.category.list
                    fields:
                        id: ~
                        name: ~
                        description:
                            type: string
                            options:
                                length: 150
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        articles:
                            type: count
                        displayInHomepage:
                            type: boolean
                        _actions: ~
                    order:
                        - {field: updatedAt, order: desc}
                    actions:
                        create:
                            title: lecomptoir.create
                            route: bluebear.cms.category.create
                            icon: plus

        article:
            entity: BlueBear\CmsBundle\Entity\Article
            form: article
            actions:
                list:
                    title: bluebear.cms.article.list
                    fields:
                        id: ~
                        title:
                            type: link
                            options:
                                length: 100
                                route: bluebear.cms.article.edit
                                parameters: {id: ~}
                        category: ~
                        author: ~
                        publicationStatus: {type: date, options: {format: d/m/Y}}
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        updatedAt: {type: date, options: {format: d/m/Y h:i:s}}
                        _actions:
                            type: collection
                            options:
                                _edit:
                                    type: action
                                    options:
                                        title: lag.admin.edit
                                        route: bluebear.cms.article.edit
                                        parameters: {id: ~}
                                        icon: pencil
                                _delete:
                                    type: action
                                    options:
                                        title: lag.admin.delete
                                        route: bluebear.cms.article.delete
                                        parameters: {id: ~}
                                        icon: remove
                                canonical:
                                    type: link
                                    options:
                                        title: lag.cms.article.see
                                        text: bluebear.cms.article.see
                                        target: _blank
                                        icon: eye

                    order:
                        - {field: publicationDate, order: desc}
                    actions:
                        create:
                            title: bluebear.admin.create
                            route: bluebear.cms.article.create
                            icon: plus
                create: ~
                edit:
                    actions:
                        preview:
                            title: bluebear.cms.article.preview
                            route: bluebear.cms.article.preview
                            parameters: {id: ~}
                            target: _blank
                            icon: eye
                delete: ~
        parameters:
            entity: BlueBear\CmsBundle\Entity\Parameters
            form: parameters
            actions:
                list:
                    fields: {id: ~, title: {type: string, options: {length: 100}}, value: {type: string, options: {length: 100}}}
                create: ~
                edit: ~
                delete: ~
        comment:
            entity: BlueBear\CmsBundle\Entity\Comment
            form: comment
            actions:
                list:
                    title: lag.cms.comments
                    fields:
                        id: ~
                        content: {type: string, options: {length: 150}}
                        article: ~
                        _actions: ~
                create: ~
                edit: ~
                delete: ~
        import:
            entity: BlueBear\CmsImportBundle\Entity\Import
            form: import
            controller: BlueBearCmsImportBundle:Import
            actions:
                list:
                    fields:
                        id: ~
                        label: {type: string, options: {length: 100}}
                        comments: {type: string, options: {length: 100}}
                        status: ~
                    actions:
                        import:
                            title: bluebear.cms.import.create
                            route: bluebear.cms.import.create
                            icon: plus
                create: ~
                edit: ~
                delete: ~

        media:
            entity: BlueBear\MediaBundle\Entity\Media
            form: media
            controller: BlueBearMediaBundle:Media
            actions:
                list:
                    fields:
                        id: ~
                        name: ~
                        filepath: ~
                        filename: ~
                        extension: ~
                        type: ~
                        updatedAt: {type: date, options: {format: d/m/Y h:i:s}}
                        _edit:
                            type: action
                            options:
                                title: bluebear.admin.edit
                                route: bluebear.cms.media.edit
                                parameters: {id: ~}
                                icon: pencil
                        _delete:
                            type: action
                            options:
                                title: bluebear.admin.delete
                                route: bluebear.cms.media.delete
                                parameters: {id: ~}
                                icon: remove
                upload: ~
                edit: ~
                delete: ~
        page:
            entity: BlueBear\CmsBundle\Entity\Page
            form: page
            actions:
                list:
                    fields:
                        id: ~
                        title: ~
                        content: ~
                        updatedAt: {type: date, options: {format: d/m/Y h:i:s}}
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        _actions:
                            type: collection
                            options:
                                edit:
                                    type: action
                                    options:
                                        title: bluebear.admin.edit
                                        route: bluebear.cms.page.edit
                                        parameters: {id: ~}
                                        icon: pencil
                                delete:
                                    type: action
                                    options:
                                        title: bluebear.admin.delete
                                        route: bluebear.cms.page.delete
                                        parameters: {id: ~}
                                        icon: remove
                    actions:
                        import:
                            title: bluebear.admin.create
                            route: bluebear.cms.page.create
                            icon: plus
                create: ~
                edit: ~
                delete: ~

bluebear_cms_import: ~

bluebear_media: ~

