#blue_bear_cms:
#    content_types:
#        # Articles
#        article:
#            fields:
#                title: ~
#                content: ~
#            behaviors:
#                authorable: ~
#                timestampable: ~
#                publishable: ~