blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~

ivory_ck_editor:
    configs:
        my_config:
            toolbar: standard
            height: 1500px

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    theme:
        simple:
            theme: "modern"
        advanced:
             theme: "modern"
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
             toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
             image_advtab: true
             menubar: false


# app/config/config.yml
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: 'LAGAdminBundle:Menu:bootstrap_menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


lag_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derrière les noisettes
        description: Des noisettes et des livres
        bootstrap: true
        base_template: 'BlueBearCmsBundle::layout.html.twig'
        max_per_page: 25
        routing:
            name_pattern: lecomptoir.cms.{admin}.{action}
            url_pattern:  /{admin}/{action}
        date_format: '\L\e d/m/Y à h:i:s'

    menus:
        main:
            items:
                category:
                    admin: category
                    icon: fa fa-folder-open
                article:
                    admin: article
                    icon: fa fa-newspaper-o
                comment:
                    admin: comment
                    icon: fa fa-comment
                page:
                    admin: page
                    icon: fa fa-code
                parameters:
                    url: '#'
                    text: Parameters
                    icon: fa fa-gear
                    items:
                        imports:
                            admin: import
                            action: list
                            icon: fa fa-upload
                media:
                    admin: media
                    icon: fa fa-image
                logout:
                    route: logout
                    icon: fa fa-sign-out

    # Admins configurations
    admins:
        ### Category ###
        category:
            entity: BlueBear\CmsBundle\Entity\Category
            form: BlueBear\CmsBundle\Form\Type\CategoryType
            actions:
                batch: ~
                create: ~
                edit: ~
                delete: ~
                list:
                    title: category.list
                    menus:
                        top:
                            items:
                                create:
                                    admin: category
                                    action: create
                                    icon: fa fa-plus
                    fields:
                        id: ~
                        name: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        articles:
                            type: count
                        displayInHomepage:
                            type: boolean
                        _actions: ~
                    order:
                        - {field: updatedAt, order: desc}

        ### Article ###
        article:
            entity: BlueBear\CmsBundle\Entity\Article
            form: BlueBear\CmsBundle\Form\Type\ArticleType
            actions:
                list:
                    title: article.list
                    order:
                        - {field: publicationDate, order: desc}
                    fields:
                        id: ~
                        title:
                            type: link
                            options:
                                length: 40
                                route: lecomptoir.cms.article.edit
                                parameters: {id: ~}
                        category: ~
                        author: ~
                        publicationStatus: ~
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        updatedAt: {type: date, options: {format: '\L\e d/m/Y à h:i:s'}}
                        _actions:
                            type: collection
                            options:
                                _edit:
                                    type: action
                                    options:
                                        title: lag.admin.edit
                                        route: lecomptoir.cms.article.edit
                                        parameters: {id: ~}
                                        icon: pencil
                                _delete:
                                    type: action
                                    options:
                                        title: lag.admin.delete
                                        route: lecomptoir.cms.article.delete
                                        parameters: {id: ~}
                                        icon: remove
                create: ~
                edit:
                    menus:
                        top:
                            items:
                                preview:
                                    text: article.preview
                                    route: bluebear.cms.article.preview
                                    parameters: {id: ~}
                                    icon: fa fa-eye
                                    attr:
                                        target: _blank

                delete: ~
        user:
            entity: BlueBear\CmsBundle\Entity\User
            form: user
            actions:
                list:
                    fields:
                        id: ~
                        username: ~
                        email: ~
                        enabled: ~
                        _actions: ~
                create: ~
                edit: ~
                delete: ~

        parameters:
            entity: BlueBear\CmsBundle\Entity\Parameters
            form: parameters
            actions:
                list:
                    fields:
                        id: ~
                        title:
                            type: string
                            options:
                                length: 100
                        value:
                            type: string
                            options:
                                length: 100
                create: ~
                edit: ~
                delete: ~
        comment:
            entity: BlueBear\CmsBundle\Entity\Comment
            form: comment
            actions:
                list:
                    title: comment.list
                    fields:
                        id: ~
                        content: {type: string, options: {length: 150}}
                        article: ~
                        _actions: ~
                    # Comments creations through backoffice is not allowed
                    menus: false
                create: ~
                edit: ~
                delete: ~
        import:
            entity: BlueBear\CmsBundle\Entity\Import
            form: import
            controller: 'BlueBearCmsBundle:Import'
            actions:
                list:
                    menus:
                        top:
                            items:
                                import:
                                    admin: import
                                    action: create
                                    icon: fa fa-upload
                    fields:
                        id: ~
                        label: {type: string, options: {length: 100}}
                        comments: {type: string, options: {length: 100}}
                        status: ~
#                    actions:
#                        import:
#                            title: bluebear.cms.import.create
#                            route: bluebear.cms.import.create
#                            icon: plus
                create: ~
                edit: ~
                delete: ~

        media:
            entity: BlueBear\MediaBundle\Entity\Media
            form: media
            controller: 'BlueBearMediaBundle:Media'
            actions:
                list:
                    fields:
                        id: ~
                        name: ~
                        filepath: ~
                        filename: ~
                        extension: ~
                        type: ~
                        updatedAt: {type: date, options: {format: 'd/m/Y h:i:s'}}
                        _edit:
                            type: action
                            options:
                                title: bluebear.admin.edit
                                route: bluebear.cms.media.edit
                                parameters: {id: ~}
                                icon: pencil
                        _delete:
                            type: action
                            options:
                                title: bluebear.admin.delete
                                route: bluebear.cms.media.delete
                                parameters: {id: ~}
                                icon: remove
                upload: ~
                edit: ~
                delete: ~
        page:
            entity: BlueBear\CmsBundle\Entity\Page
            form: page
            actions:
                list:
                    fields:
                        id: ~
                        title: ~
                        content: ~
                        updatedAt: {type: date, options: {format: 'd/m/Y h:i:s'}}
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        _actions:
                            type: collection
                            options:
                                edit:
                                    type: action
                                    options:
                                        title: bluebear.admin.edit
                                        route: bluebear.cms.page.edit
                                        parameters: {id: ~}
                                        icon: pencil
                                delete:
                                    type: action
                                    options:
                                        title: bluebear.admin.delete
                                        route: bluebear.cms.page.delete
                                        parameters: {id: ~}
                                        icon: remove
#                    actions:
#                        import:
#                            title: bluebear.admin.create
#                            route: bluebear.cms.page.create
#                            icon: plus
                create: ~
                edit: ~
                delete: ~

bluebear_media: ~

# rss/atom feed bundle
eko_feed:
    feeds:
        article:
            title: Le Comptoir de L'Ecureuil - Articles
            description: Voici les articles du comptoir de l'écureuil
            link:
                route_name: lecomptoir.feed
            encoding: utf-8
