blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~


bluebear_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derrière les noisettes
        description: Des noisettes et des livres
        bootstrap: true
        layout: BlueBearCmsBundle::layout.html.twig
        routing:
            name_pattern: bluebear.cms.{admin}.{action}
            url_pattern:  /{admin}/{action}
        date_format: d/m/Y h:i:s
    admins:
        user:
            entity: BlueBear\CmsUserBundle\Entity\User
            form: user
            actions:
                list:
                    fields: {id: ~, username: ~, email: ~, enabled: ~}
                create: ~
                edit: ~
                delete: ~

        category:
            entity: BlueBear\CmsBundle\Entity\Category
            form: category
            actions:
                list:
                    fields: {id: ~, name: ~, updatedAt: {format: Y m d}}
                    order:
                        - {field: updatedAt, order: asc}
                create: ~
                edit: ~
                delete: ~
        article:
            entity: BlueBear\CmsBundle\Entity\Article
            form: article
            actions:
                list:
                    fields: {id: ~, title: {length: 20}, category: ~, canonical: ~, publicationStatus: ~, publicationDate: {format: d/m/Y}}
                    actions:
                        create:
                            title: bluebear.admin.create
                            route: bluebear.cms.article.create
                            icon: plus
                create: ~
                edit:
                    actions:
                        preview:
                            title: bluebear.cms.article.preview
                            route: bluebear.cms.article.preview
                            parameters: {id: ~}
                            target: _blank
                            icon: eye
                delete: ~
        comment:
             entity: BlueBear\CmsBundle\Entity\Comment
             form: comment
             actions:
                 list:
                     fields: {id: ~, content: {length: 20}, article: ~}
                 create: ~
                 edit: ~
                 delete: ~
        parameters:
            entity: BlueBear\CmsBundle\Entity\Parameters
            form: parameters
            actions:
                list:
                    fields: {id: ~, title: {length: 100}, value: {length: 100}}
                create: ~
                edit: ~
                delete: ~
#        media:
#            entity: BlueBear\MediaBundle\Entity\Media
#            form: media
#            controller: BlueBearMediaBundle:Media
#            actions:
#                list:
#                    fields: {id: ~, label: ~}
#                upload: ~
