blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~

