imports:
    - { resource: admin/category.yml }
    - { resource: admin/article.yml }

blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~

ivory_ck_editor:
    configs:
        my_config:
            toolbar: standard
            height: 1500px

#stfalcon_tinymce:
#    include_jquery: false
#    tinymce_jquery: false
#    external_plugins:
#        imagetools:
#            url: 'asset[bundles/bluebearcms/js/tinymce/plugins/imagetools/plugin.js]'
#    theme:
#        simple:
#            theme: "modern"
#        advanced:
#             theme: "modern"
#             plugins:
#                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
#                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
#                 - "insertdatetime media nonbreaking save table contextmenu directionality"
#                 - "emoticons template paste textcolor"
#             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#             toolbar2: "print preview media | forecolor backcolor emoticons | imagetools"
#             image_advtab: true
#             menubar: true
#             imagetools_cors_hosts: ['dev.le-comptoir.fr', 'lecomptoir.bluebear.fr']
#             imagetools_proxy: 'proxy.php'
#             imagetools_toolbar: "imageoptions"


# app/config/config.yml
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: 'LAGAdminBundle:Menu:bootstrap_menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


lag_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derrière les noisettes
        description: Des noisettes et des livres
        bootstrap: true
        base_template: 'BlueBearCmsBundle::layout.html.twig'
        max_per_page: 25
        routing:
            name_pattern: cms.{admin}.{action}
            url_pattern:  /cms/{admin}/{action}
        date_format: '\L\e d/m/Y à h:i:s'

    menus:
        main:
            items:
                category:
                    admin: category
                    icon: fa fa-folder-open
                article:
                    admin: article
                    icon: fa fa-newspaper-o
                comment:
                    admin: comment
                    icon: fa fa-comment
                page:
                    admin: page
                    icon: fa fa-code
                partners:
                    admin: partner
                    icon: fa fa-book
                parameters:
                    url: '#'
                    text: Parameters
                    icon: fa fa-gear
                    items:
                        imports:
                            admin: import
                            action: list
                            icon: fa fa-upload
                media:
                    admin: media
                    icon: fa fa-image
                logout:
                    route: logout
                    icon: fa fa-sign-out

    # Admins configurations
    admins:
        ### User ###
        user:
            entity: BlueBear\CmsBundle\Entity\User
            form: BlueBear\CmsBundle\Form\Type\UserType
            actions:
                list:
                    fields:
                        id: ~
                        username: ~
                        email: ~
                        enabled: ~
                        _actions: ~
                create: ~
                edit: ~
                delete: ~

        parameters:
            entity: BlueBear\CmsBundle\Entity\Parameters
            form: BlueBear\CmsBundle\Form\Type\ParametersType
            actions:
                list:
                    fields:
                        id: ~
                        title:
                            type: string
                            options:
                                length: 100
                        value:
                            type: string
                            options:
                                length: 100
                create: ~
                edit: ~
                delete: ~
        comment:
            entity: BlueBear\CmsBundle\Entity\Comment
            form: BlueBear\CmsBundle\Form\Type\CommentType
            actions:
                list:
                    title: comment.list
                    fields:
                        id: ~
                        content: {type: string, options: {length: 150}}
                        article: ~
                        _actions: ~
                    # Comments creations through backoffice is not allowed
                    menus: false
                create: ~
                edit: ~
                delete: ~
        import:
            entity: BlueBear\CmsBundle\Entity\Import
            form: BlueBear\CmsBundle\Form\Type\ImportType
            controller: 'BlueBearCmsBundle:Import'
            actions:
                list:
                    menus:
                        top:
                            items:
                                import:
                                    admin: import
                                    action: create
                                    icon: fa fa-upload
                    fields:
                        id: ~
                        label: {type: string, options: {length: 100}}
                        comments: {type: string, options: {length: 100}}
                        status: ~
#                    actions:
#                        import:
#                            title: bluebear.cms.import.create
#                            route: bluebear.cms.import.create
#                            icon: plus
                create: ~
                edit: ~
                delete: ~

        media:
            entity: BlueBear\MediaBundle\Entity\Media
            form: BlueBear\CmsBundle\Form\Type\MediaType
            controller: 'BlueBearMediaBundle:Media'
            actions:
                list:
                    fields:
                        id: ~
                        name: ~
                        filepath: ~
                        filename: ~
                        extension: ~
                        type: ~
                        updatedAt: {type: date, options: {format: 'd/m/Y h:i:s'}}
                        _edit:
                            type: action
                            options:
                                title: bluebear.admin.edit
                                route: lecomptoir.cms.media.edit
                                parameters: {id: ~}
                                icon: pencil
                        _delete:
                            type: action
                            options:
                                title: bluebear.admin.delete
                                route: lecomptoir.cms.media.delete
                                parameters: {id: ~}
                                icon: remove
                upload: ~
                edit: ~
                delete: ~
        page:
            entity: BlueBear\CmsBundle\Entity\Page
            form: BlueBear\CmsBundle\Form\Type\PageType
            actions:
                list:
                    fields:
                        id: ~
                        title:
                            type: link
                            options:
                                length: 40
                                route: cms.page.edit
                                parameters: {id: ~}
                        content:
                            options:
                                 length: 150
                        updatedAt: {type: date, options: {format: 'd/m/Y h:i:s'}}
                        publicationDate: {type: date, options: {format: d/m/Y}}
                        _actions:
                            type: collection
                            options:
                                _edit:
                                    type: action
                                    options:
                                        title: lag.admin.edit
                                        route: cms.page.edit
                                        parameters: {id: ~}
                                        icon: pencil
                                _delete:
                                    type: action
                                    options:
                                        title: lag.admin.delete
                                        route: cms.page.delete
                                        parameters: {id: ~}
                                        icon: remove
#                    actions:
#                        import:
#                            title: bluebear.admin.create
#                            route: bluebear.cms.page.create
#                            icon: plus
                create: ~
                edit:
                    title: cms.page.edit.form_title
                delete: ~
        partner:
            entity: AppBundle\Entity\Partner
            form: AppBundle\Form\Type\PartnerType

bluebear_media: ~

# rss/atom feed bundle
eko_feed:
    feeds:
        article:
            title: Le Comptoir de L'Ecureuil - Articles
            description: Voici les articles du comptoir de l'écureuil
            link:
                route_name: lecomptoir.feed
            encoding: utf-8

# File Upload
vich_uploader:
    db_driver: orm
    mappings:
        article_media:
            uri_prefix: /images/articles/thumbnails
            upload_destination: '%kernel.root_dir%/../web/images/articles/thumbnails'
