imports:
    - { resource: config.yml }

parameters:
    security.requires_channel: null

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

hautelook_alice:
    db_drivers:
        orm: ~
    locale: fr_FR

swiftmailer:
    delivery_address: '%admin_mail%'
