imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

# Monolog Configuration
monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/bluebear-%kernel.environment%.log"
            level: error

#ekino_new_relic:
#    enabled: true
#    application_name: LeComptoir
#    deployment_names: ~
#    api_key:
#    license_key:
#    xmit: false
#    logging: false
#    instrument: false
#    log_exceptions: false
#    log_commands: true
#    using_symfony_cache: false
#    transaction_naming: route
#    transaction_naming_service: ~
#    ignored_routes: []
#    ignored_paths: []
#    ignored_commands: []

jk_assets:
    debug: true
    filters:
        compass:
            bin: /usr/local/bin/compass
        merge: ~
        minify: ~
        copy: ~
    tasks:
        build.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - app/Resources/assets/sass/main.scss
            destinations:
                - web/css/main.css

        bootstrap:
            filters:
                - copy
            sources:
                # bootstrap
                - vendor/components/bootstrap/css/bootstrap.min.css
                - vendor/components/bootstrap/css/bootstrap-theme.min.css
                - vendor/components/bootstrap/js/bootstrap.min.js
                - vendor/components/bootstrap/fonts/*
                # font-awesome
                - vendor/components/font-awesome/css/font-awesome.min.css
                - vendor/components/font-awesome/fonts/*
            destinations:
                # bootstrap
                - web/css/bootstrap.min.css
                - web/css/bootstrap-theme.min.css
                - web/js/bootstrap.min.js
                - web/fonts/
                # font-awesome
                - web/css/font-awesome.min.css
                - web/fonts/
