imports:
    - { resource: config.yml }

# Monolog Configuration
monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/bluebear-%kernel.environment%.log"
        nested:
            type: rotating_file
            path: 'php://stderr'
            level: error
