imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: cms.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallbacks: [en] }
    assets: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "fr"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "LAGAdminBundle:Form:fields.html.twig"
        - "BlueBearCmsBundle:Form:fields.html.twig"

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - BlueBearCmsBundle
        - AppBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        compass:
            images_dir:            %kernel.root_dir%/../web/img
            generated_images_path: %kernel.root_dir%/../web/img
            compass.http_path: img/
        jsminplus: ~
        cssmin: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Monolog Configuration
monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/bluebear-%kernel.environment%.log"
            level: error


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: false


# app/config/config.yml
knp_gaufrette:
    adapters:
        local_adapter:
            local:
                directory: %database_backup_path%

    filesystems:
        local_backup_filesystem:
            adapter:    local_adapter
            alias:      local_backup_filesystem

dizda_cloud_backup:
    # By default backup files will have your servers hostname as prefix
    # such as: hostname_2014-01-01_21-08-39.tar
    output_file_prefix: backup_%database_name%
    timeout: 300
    processor:
        type: 7z # Required: tar|zip|7z
        options:
            compression_ratio: 6
            # Split into many files of `split_size` bytes
    #folders:
    #    - dumps
    cloud_storages:
        # Local storage definition
        local:
            path: dumps
        # CloudApp account. Can be optional, like dropbox.
#        cloudapp:
#            user:        ~ # Required
#            password:    ~ # Required
        # or you can use Gaufrette as well (optional)
        gaufrette:
            service_name:   # Gaufrette filesystem(s) service name
                - local_backup_filesystem
#        google_drive:
#          token_name: ~ # Required
#          remote_path: ~ # Not required, default "/", but you can use path like "/Accounts/backups/"
        # Using dropbox via official API. You need to add "dropbox/dropbox-sdk": "1.1.*" in your composer.json file

    databases:
        mysql:
            all_databases: false # Only required when no database is set
            database: %database_name%
            db_host: %database_host%
            db_port: %database_port%
            db_user: %database_user%
            db_password: %database_password%

