imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

hautelook_alice:
    db_drivers:
        orm: ~
    locale: fr_FR
    seed: 1
    persist_once: false
    loading_limit: 5
