imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu
