imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

# Monolog Configuration
monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 5
            path: "%kernel.logs_dir%/bluebear-%kernel.environment%.log"
            level: error

#ekino_new_relic:
#    enabled: true
#    application_name: LeComptoir
#    deployment_names: ~
#    api_key:
#    license_key:
#    xmit: false
#    logging: false
#    instrument: false
#    log_exceptions: false
#    log_commands: true
#    using_symfony_cache: false
#    transaction_naming: route
#    transaction_naming_service: ~
#    ignored_routes: []
#    ignored_paths: []
#    ignored_commands: []
