# BlueBear AdminBundle
blue_bear_admin:
    resource: .
    prefix: /cms
    type: extra

blue_bear_cms:
    resource: "@BlueBearCmsBundle/Resources/config/routing.yml"
    prefix:   /cms

le_comptoir_de_l_ecureuil_front:
    resource: "@LeComptoirDeLEcureuilFrontBundle/Resources/config/routing.yml"
    prefix:   /

blue_bear_media:
    resource: "@BlueBearMediaBundle/Resources/config/routing.yml"
    prefix:   /cms
