blue_bear_cms_import:
    resource: "@BlueBearCmsImportBundle/Resources/config/routing.yml"
    prefix:   /

blue_bear_cms_user:
    resource: "@BlueBearCmsUserBundle/Resources/config/routing.yml"
    prefix:   /

le_comptoir_de_l_ecureuil_front:
    resource: "@LeComptoirDeLEcureuilFrontBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear AdminBundle
blue_bear_admin:
    resource: .
    prefix: /cms
    type: extra

blue_bear_cms:
    resource: "@BlueBearCmsBundle/Resources/config/routing.yml"
    prefix:   /cms

blue_bear_media:
    resource: "@BlueBearMediaBundle/Resources/config/routing.yml"
    prefix:   /cms

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /cms