jk_cms:
    resource: "@JKCmsBundle/Resources/config/routing.yml"
    prefix:   /

jk_database:
    resource: "@JKDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

# BlueBear AdminBundle
blue_bear_admin:
    resource: .
    prefix: /
    type: extra

blue_bear_cms:
    resource: "@BlueBearCmsBundle/Resources/config/routing.yml"
    prefix:   /

le_comptoir_de_l_ecureuil_front:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

blue_bear_media:
    resource: "@BlueBearMediaBundle/Resources/config/routing.yml"
    prefix:   /
