blue_bear_cms_user:
    resource: "@BlueBearCmsUserBundle/Resources/config/routing.yml"
    prefix:   /

le_comptoir_de_l_ecureuil_front:
    resource: "@LeComptoirDeLEcureuilFrontBundle/Resources/config/routing.yml"
    prefix:   /

blue_bear_cms:
    resource: "@BlueBearCmsBundle/Resources/config/routing.yml"
    prefix:   /admin/cms

# BlueBear AdminBundle
blue_bear_admin:
    resource: .
    type: extra

le_comptoir_de_l_ecureuil_back:
    resource: "@LeComptoirDeLEcureuilBackBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"