# OAuth
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    path: /login/check-google

jk_cms:
    resource: '@JKCmsBundle/Resources/config/routing.yml'
    prefix:   /cms

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

jk_database:
    resource: '@JKDatabaseBundle/Resources/config/routing.yml'
    prefix:   /

admin_bundle:
    resource: '@LAGAdminBundle/Resources/config/routing.yml'
    prefix: /cms

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /

cms.media.add_image_modal:
    path: /cms/media/add-image
    defaults: {_controller: JK\CmsBundle\Action\Media\AddImageModal}

oneup_uploader:
    resource: .
    type: uploader
    prefix: /cms

blue_bear_media:
    resource: '@BlueBearMediaBundle/Resources/config/routing.yml'
    prefix:   /

