security:
    encoders:
        BlueBear\CmsBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_OAUTH_USER:  ROLE_ADMIN
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        cms_user_provider:
            id: google.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path: /cms/logout
            oauth:
                resource_owners:
                    google:   /login/check-google
                login_path:   /login
                failure_path: /login
                default_target_path: /cms/dashboard
                use_forward:  false
                oauth_user_provider:
                    service: google.user_provider

    access_control:
        - {path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_scheme%'}
        - {path: ^/connect/google, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_scheme%'}
        - {path: ^/cms, role: ROLE_ADMIN, requires_channel: '%http_scheme%'}
        - {path: ^/article/, role: ROLE_ADMIN, requires_channel: '%http_scheme%'}
        - {path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_scheme%'}
