security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:   ^/cms/(login$|register|resetting)
            anonymous: true

        main:
            pattern: ^/cms
            form_login:
                check_path: /cms/login_check
                login_path: /cms/login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /cms/dashboard
                always_use_default_target_path: true
            logout:
                path:   /cms/logout
                target: /
            anonymous:    false

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cms/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cms/, role: ROLE_ADMIN }
