security:
    encoders:
        BlueBear\CmsBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        cms_user_provider:
            id: cms_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/(cms)|(article/(\d+)/preview)
            anonymous: ~
            logout:
                path: /cms/logout
                target: /cms/login

            guard:
                authenticators:
                    - cms_authenticator

    access_control:
        - { path: ^/cms/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cms/, role: ROLE_ADMIN }
        - { path: ^/article/    , role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
