parameters:

services:
    cms_user_provider:
        class: BlueBear\CmsBundle\Guard\UserProvider\UserProvider
        arguments:
            - '@jk.cms.user_repository'

    cms_authenticator:
        class: BlueBear\CmsBundle\Guard\Authenticator\TokenAuthenticator
        arguments:
            - '@router'
            - '@form.factory'
            - '@security.encoder_factory'

    google.user_provider:
        class: AppBundle\Google\UserProvider
        autowire: true
        arguments:
            - '%google_allowed_users%'
