version: '2'

services:
    www:
        container_name: le_comptoir_www
        image: nginx
        links:
            - php
            - db
        ports:
            - ${DOCKER_HTTP_PORT}:80
        volumes:
          - ./www/nginx/conf.d/:/etc/nginx/conf.d/
          - ./../../var/logs/nginx/:/var/log/nginx/
        volumes_from:
          - php
        environment:
            SF_DATABASE_HOST: db
            SF_DATABASE_PORT: 3306
            SF_DATABASE_NAME: ${DOCKER_DATABASE_NAME}
            SF_DATABASE_USER: ${DOCKER_DATABASE_USER}
            SF_DATABASE_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
            SF_MAILER_TRANSPORT: smtp
            SF_MAILER_HOST: 'mailcatcher:1025'
            SF_MAILER_USER: '~'
            SF_MAILER_PASSWORD: '~'
            SF_LOCALE: fr
        stdin_open: true
        tty: true

    php:
        container_name: le_comptoir_php
        working_dir: /var/www/current
        build: php
        ports:
            - 9000:9000
        links:
            - db
        volumes:
            - '../../:/var/www/current'

    db:
        container_name: le_comptoir_db
        image: mariadb
        ports:
            - ${DOCKER_DATABASE_PORT}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${DOCKER_DATABASE_NAME}
            MYSQL_USER: ${DOCKER_DATABASE_USER}
            MYSQL_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
