lecomptoir.homepage:
    path:     /
    defaults: {_controller: AppBundle:Main:index}

lecomptoir.contact:
    path: /contact
    defaults: {_controller: AppBundle:Main:contact}

lecomptoir.about:
    path: /a-propos
    defaults: {_controller: AppBundle:Main:whoAmI}

lecomptoir.legal:
    path: /mentions-legales
    defaults: {_controller: AppBundle:Main:legal}

lecomptoir.feed:
    path: /feed
    defaults: {_controller: AppBundle:Main:feed}

# Partners pages
lecomptoir.partner:
    path: /partenaires/{partnerSlug}
    defaults: {_controller: AppBundle:Main:partner}

# Articles Pages
lecomptoir.article.list_by_category:
    path: /category/{categorySlug}
    defaults: {_controller: AppBundle:Article:filter}

lecomptoir.article.list_by_tag:
    path: /tag/{tagSlug}
    defaults: {_controller: AppBundle:Article:filter}

lecomptoir.article.unsubscribe:
    path: /{slug}/{email}/unsubscribe
    defaults: {_controller: AppBundle:Article:unsubscribe}

# Article preview
lecomptoir.article.preview:
    path: /article/{id}/preview
    defaults: {_controller: AppBundle:Article:preview}

lecomptoir.article.show:
    path:  /{year}/{month}/{slug}
    defaults: {_controller: AppBundle:Article:show}

# fix for bad wordpress urls
lecomptoir.article.show2:
    path:  /{year}/{month}/{slug}/
    defaults: {_controller: AppBundle:Article:show}

# Sitemap
lecomptoir.sitemap:
    path: /sitemap.xml
    defaults: {_controller: AppBundle:Main:sitemap}

# Free Pages
lecomptoir.free_pages:
    path: /{pageSlug}
    defaults: {_controller: AppBundle:Page:show}

