services:
    app_partner_repository:
        class: App\Repository\PartnerRepository
        factory:
            - '@doctrine'
            - getRepository
        arguments:
            - App\Entity\Partner

    app_sitemap_generator:
        class: App\Sitemap\Generator
        arguments:
            - '%kernel.cache_dir%'
            - '@router'
            - '@cms.article.repository'
            - '@twig'

    app_comment_form_handler:
        class: App\Form\Handler\CommentHandler
        arguments:
            - '@jk.cms.comment_repository'
