---
- hosts: all
  user: '{{ user }}'
  become: yes

  tasks:
    - name: Dump a backup from the remote database
      mysql_db:
        state: dump
        name: '{{ database_name }}'
        target: /home/{{ user }}/tmp/{{ database_name }}.sql
        login_user: '{{ database_user }}'
        login_password: '{{ database_password }}'

    - name: Copy the remote backup file on the local filesystem
      fetch:
        src: /home/{{ user }}/tmp/{{ database_name }}.sql
        dest: /tmp/ansible/database/{{ database_name }}.sql
        flat: true

    - name: Remove the remote backup file
      file:
        state: absent
        path: /home/{{ user }}/tmp/{{ database_name }}.sql

    - name: Load the backup on the local database
      delegate_to: 127.0.0.1
      become: no
      mysql_db:
        state: import
        target: /tmp/ansible/database/{{ database_name }}.sql
        name: '{{ database_local_name }}'
        login_user: '{{ database_local_user }}'
        login_password: '{{ database_local_password }}'

    - name: Remove the local backup file
      delegate_to: 127.0.0.1
      become: no
      file:
        state: absent
        path: /tmp/ansible/database/{{ database_name }}.sql
