---
- hosts: all
  user: lecomptoirdelecureuil

  roles:
    - carlosbuenosvinos.ansistrano-deploy

  vars:
    # Username
    user: lecomptoirdelecureuil
    database_name: le-comptoir

    # Ansistrano
    ansistrano_deploy_from: '{{ playbook_dir }}'
    ansistrano_deploy_to: '/home/{{ user }}/www/{{ user }}'
    ansistrano_version_dir: 'releases'
    ansistrano_current_dir: 'current'
    ansistrano_current_via: 'symlink'
    ansistrano_shared_paths: []
    ansistrano_keep_releases: 5
    ansistrano_deploy_via: 'git'
    ansistrano_allow_anonymous_stats: yes
    ansistrano_git_repo: git@github.com:johnkrovitch/LeComptoirDeLEcureuil.git
    ansistrano_git_branch: dev
    ansistrano_git_identity_key_path: '~/.ssh/id_rsa'
    ansistrano_after_update_code_tasks_file: '{{ playbook_dir}}/../tasks/install-symfony.yml'


    # Symfony
    symfony_env: prod
    symfony_php_path: php # The PHP executable to use for all command line tasks

    symfony_run_composer: true
    symfony_composer_path: "{{ ansistrano_deploy_to }}/composer.phar"
    symfony_composer_options: '--dev --optimize-autoloader --no-interaction'
    symfony_composer_self_update: true
    symfony_console: "{{ ansistrano_release_path.stdout }}/bin/console"

    symfony_run_assets_install: true
    symfony_assets_options: '--no-interaction'

    symfony_run_assetic_dump: true
    symfony_assetic_options: '--no-interaction'

    symfony_run_cache_clear_and_warmup: true
    symfony_cache_options: ''

    ###############################################################################
    symfony_run_doctrine_migrations: false
    symfony_doctrine_options: '--no-interaction'



  tasks:
