---
- hosts: all

  tasks:
       - include_tasks: ../tasks/deploy/init.yml
       - include_tasks: ../tasks/deploy/git.yml
       - include_tasks: ../tasks/deploy/symfony.init.yml
       - include_tasks: ../tasks/deploy/shared.yml
       - include_tasks: ../tasks/deploy/composer.yml
       - include_tasks: ../tasks/deploy/symfony.yml
       - include_tasks: ../tasks/deploy/finalize.yml
