---
- hosts: all
  user: lecomptoirdelecureuil
  vars:
    ansible_user: lecomptoirdelecureuil

  tasks:
    - name: Initialize the deploy structure
      deploy_helper: path={{ deploy_path }}

    - name: Clone the new release
      git:
        repo=git@github.com:johnkrovitch/LeComptoirDeLEcureuil.git
        dest={{ deploy_helper.new_release_path }}
        version={{ git_version }}

    - name: Create Symfony's parameters.yml
      template: src=../templates/parameters.yml.j2
            dest={{ deploy_helper.new_release_path }}/app/config/parameters.yml
            force=yes
            owner={{ user }}

    - name: Add an unfinished file, to allow cleanup on successful finalize
      file:
        path={{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}
        state=touch

    - name: Run composer update
      composer:
        command=update
        working_dir={{ deploy_helper.new_release_path }}
        no_dev=no
        optimize_autoloader=yes

    - name: Update database schema (using migrations)
      shell: '{{ deploy_helper.new_release_path }}/bin/console doctrine:migrations:migrate --no-interaction'

    - name: Create folders in the shared folder
      file:
        path={{ deploy_helper.shared_path }}/{{ item }}
        state=directory
      with_items:
        - 'var/logs'
        - 'web/images'

    - name: Add symlinks from the new release to the shared folder
      file:
        path='{{ deploy_helper.new_release_path }}/{{ item.path }}'
        src='{{ deploy_helper.shared_path }}/{{ item.src }}'
        state=link
        force=yes
      with_items:
        - { path: 'var/logs', src: "var/logs" }
        - { path: 'web/images', src: "web/images" }
        - { path: 'uploads', src: "uploads" }

    - name: Cache warmup
      shell: '{{ deploy_helper.new_release_path }}/bin/console cache:warmup --env=prod'

    - name: Finalize the deploy, removing the unfinished file and switching the symlink
      deploy_helper:
        path='{{ deploy_path }}'
        release={{ deploy_helper.new_release }}
        state=finalize
        keep_releases=5
