- name: Run with inline v2 compose
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - docker_service:
        project_name: le-comptoir
        definition:
          version: '2'
          services:
            db:
              image: mariadb
              ports:
                - 3366:8080
              volumes:
                - ./data/mysql:/var/lib/mysql
              environment:
                MYSQL_RANDOM_ROOT_PASSWORD: 'no'
                MYSQL_DATABASE: le_comptoir
                MYSQL_USER: le_comptoir
                MYSQL_PASSWORD: le_comptoir_password
#            app:
#              build: "{{ playbook_dir }}/flask"
#              command: "python manage.py runserver 0.0.0.0:8000"
#              volumes:
#                - "{{ playbook_dir }}/flask:/code"
#              ports:
#                - "8000:8000"
#              depends_on:
#                - db
#      register: output
#
#    - debug:
#        var: output
#
#    - assert:
#        that:
#          - "web.flask_web_1.state.running"
#          - "db.flask_db_1.state.running"
