services:
    jk.cms.comment_repository:
        class: App\Repository\CommentRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Comment

    jk.cms.category_repository:
        class: App\Repository\CategoryRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Category

    jk.cms.user_repository:
        class: App\Repository\UserRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\User

    jk.cms.tag_repository:
        class: App\Repository\TagRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Tag

    jk.cms.import_repository:
        class: App\Repository\ImportRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Import

    jk.cms.page_repository:
        class: App\Repository\PageRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Page
