lecomptoir.homepage:
    path:     /
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Main:index}

lecomptoir.contact:
    path: /contact
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Main:contact}

lecomptoir.partners:
    path: /partenaires
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Main:partners}

lecomptoir.partner:
    path: /partenaires/{partnerSlug}
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Main:partners}

lecomptoir.article.show:
    path:  /{year}/{month}/{slug}
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Article:show}

lecomptoir.article.list_by_category:
    path: /category/{categorySlug}
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Article:filter}

lecomptoir.article.list_by_tag:
    path: /tag/{tag}
    defaults: {_controller: LeComptoirDeLEcureuilFrontBundle:Article:filter}
