lecomptoir.homepage:
    path:     /
    defaults: { _controller: LeComptoirDeLEcureuilFrontBundle:Main:index }

lecomptoir.article.show:
    path:  /{year}/{month}/{slug}
    defaults: { _controller: LeComptoirDeLEcureuilFrontBundle:Article:filter }

lecomptoir.article.list_by_category:
    path: /{categorySlug}
    defaults: { _controller: LeComptoirDeLEcureuilFrontBundle:Article:filter }
