lecomptoir.homepage:
    path:     /
    defaults: { _controller: LeComptoirDeLEcureuilFrontBundle:Main:index }

lecomptoir.article.show:
    path:  /article/{year}/{month]/{slug}

lecomptoir.article.listByCategory:
    path: /{categorySlug}
    defaults: { _controller: LeComptoirDeLEcureuilFrontBundle:Article:listByCategorie }
