

blue_bear_cms:
    content:
        # available content behaviors: authorable, timestampable, publishable, commentable
        types:
            Page:
                fields:
                    title: ~
                    content: ~
                    description: ~
                    canonical: ~
                behaviors:
                    authorable: ~
                    timestampable: ~
                    publishable: ~
            Article:
                parent: Page
                behaviors:
                  commentable: ~
knp_menu:
    twig:
        template: 'LAGAdminBundle:Menu:bootstrap_menu.html.twig'
    templating: false
    default_renderer: twig

lag_admin:
    application:
        title: Le Comptoir De L'Ecureuil, derrière les noisettes
        description: Des noisettes et des livres
        bootstrap: true
        base_template: 'BlueBearCmsBundle::layout.html.twig'
        max_per_page: 25
        routing:
            name_pattern: cms.{admin}.{action}
            # CmsBundle already have "cms" prefix
            url_pattern:  /{admin}/{action}
        date_format: '\L\e d/m/Y à h:i:s'
        translation:
            enabled: true
            pattern: cms.{admin}.{key}
    menus:
        main:
            items:
                category:
                    admin: category
                    icon: fa fa-folder-open
                article:
                    admin: article
                    icon: fa fa-newspaper-o
                tag:
                    admin: tag
                    icon: fa fa-tags
                media:
                    admin: media
                    icon: fa fa-image
                comment:
                    admin: comment
                    icon: fa fa-comment
                page:
                    admin: page
                    icon: fa fa-code
                partners:
                    admin: partner
                    icon: fa fa-book
                    text: lecomptoir.partner.list
                parameters:
                    url: '#'
                    text: Parameters
                    icon: fa fa-gear
                    items:
                        imports:
                            admin: import
                            action: list
                            icon: fa fa-upload
                logout:
                    route: logout
                    icon: fa fa-sign-out

    # Admins configurations
    admins:
        ### User ###
        user:
            entity: App\Entity\User
            form: App\Form\Type\UserType
            actions:
                list:
                    fields:
                        id: ~
                        username: ~
                        email: ~
                        enabled: ~
                        _actions: ~
                create: ~
                edit: ~
                delete: ~

        parameters:
            entity: App\Entity\Parameters
            form: App\Form\Type\ParametersType
            actions:
                list: ~
                create: ~
                edit: ~
                delete: ~

        import:
            entity: App\Entity\Import
            form: App\Form\Type\ImportType
            controller: 'BlueBearCmsBundle:Import'
            actions:
                list:
                    menus:
                        top:
                            items:
                                import:
                                    admin: import
                                    action: create
                                    icon: fa fa-upload
                    fields:
                        id: ~
                        label: {type: string, options: {length: 100}}
                        comments: {type: string, options: {length: 100}}
                        status: ~
                create: ~
                edit: ~
                delete: ~
        partner:
            entity: AppBundle\Entity\Partner
            form: AppBundle\Form\Type\PartnerType
            actions: []



