### HWI OAuth ###
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

app.login.google:
    path: /login/check-google
#################


### Cms ###
app.cms.homepage:
    path: /cms
    defaults: {_controller: App\Controller\Cms\HomepageAction}

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'
###########

oneup_uploader:
    resource: .
    type: uploader
    prefix: /cms

cms.media.add_image_modal:
    path: /cms/media/add-image
    defaults: {_controller: JK\CmsBundle\Action\Media\AddImageModal}

## BlueBear AdminBundle
#jk_admin:
#    resource: .
#    prefix: /cms
#    type: extra

#blue_bear_cms:
#    resource: '@BlueBearCmsBundle/Resources/config/routing.yml'
#    prefix:   /cms
#
#le_comptoir_de_l_ecureuil_front:
#    resource: '@AppBundle/Resources/config/routing.yml'
#    prefix:   /
#
#blue_bear_media:
#    resource: '@BlueBearMediaBundle/Resources/config/routing.yml'
#    prefix:   /

# Guard
#login:
#    path: /login
#    defaults: {_controller: 'BlueBearCmsBundle:Guard:login'}
#
#login_check:
#    path: /login_check
#    defaults: {_controller: 'BlueBearCmsBundle:Guard:loginCheck'}
#
#logout:
#    path: /logout

# Cms
#bluebear.cms.homepage:
#    path: /
#    defaults: {_controller: 'JKCmsBundle:Dashboard:dashboard'}
#
#bluebear.cms.article.preview:
#    path: /article/preview/{id}
#    defaults: {_controller: 'BlueBearCmsBundle:Article:preview'}
#
## Image
#cms.image.gallery_dialog:
#    path: /images/gallery/dialog
#    defaults: {_controller: 'BlueBearCmsBundle:Image:galleryDialog'}
