### App ###
lecomptoir.homepage:
    path: /
    defaults: {_controller: App\Controller\HomepageAction}
###########

### HWI OAuth ###
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /cms/redirect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /cms/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /cms/login

app.login.google:
    path: /cms/login/check-google
#################

### Cms ###
lecomptoir.cms.homepage:
    path: /cms
    defaults: {_controller: App\Controller\Cms\HomepageAction}

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'
###########

oneup_uploader:
    resource: .
    type: uploader
    prefix: /cms

cms.media.add_image_modal:
    path: /cms/media/add-image
    defaults: {_controller: JK\CmsBundle\Action\Media\AddImageModal}

### AdminBundle ###
jk_admin:
    resource: .
    prefix: /cms
    type: extra
###################

#blue_bear_cms:
#    resource: '@BlueBearCmsBundle/Resources/config/lecomptoir.yaml'
#    prefix:   /cms
#
#
#blue_bear_media:
#    resource: '@BlueBearMediaBundle/Resources/config/lecomptoir.yaml'
#    prefix:   /

# Guard
#login:
#    path: /login
#    defaults: {_controller: 'BlueBearCmsBundle:Guard:login'}
#
#login_check:
#    path: /login_check
#    defaults: {_controller: 'BlueBearCmsBundle:Guard:loginCheck'}
#
#logout:
#    path: /logout

# Cms
#bluebear.cms.homepage:
#    path: /
#    defaults: {_controller: 'JKCmsBundle:Dashboard:dashboard'}
#
#bluebear.cms.article.preview:
#    path: /article/preview/{id}
#    defaults: {_controller: 'BlueBearCmsBundle:Article:preview'}
#
## Image
#cms.image.gallery_dialog:
#    path: /images/gallery/dialog
#    defaults: {_controller: 'BlueBearCmsBundle:Image:galleryDialog'}
