parameters:
    locale: 'fr'
    google_analytics_id: '%env(GOOGLE_ANALYTICS_ID)%'
    hotjar_enabled: '%env(HOTJAR_ENABLED)%'
    delivery_address: '%env(DELIVERY_ADDRESS)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    google_scope: '%env(GOOGLE_SCOPE)%'
    google_allowed_users: '%env(GOOGLE_ALLOWED_USERS)%'
    google.recaptcha.site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google.recaptcha.secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $googleAllowedUser: '%google_allowed_users%'
            $kernelEnvironment: '%kernel.environment%'
            $rootDirectory: '%kernel.root_dir%'
            $googleRecaptchaSiteKey: '%google.recaptcha.site_key%'
            $googleRecaptchaSecret: '%google.recaptcha.secret%'
            $assetsMapping: '%cms.assets.mapping%'
            $uploadDirectory: '%kernel.project_dir%/public/uploads'
            $cacheDirectory: '%kernel.cache_dir%'
            $administratorEmail: '%env(APP_ADMINISTRATOR_EMAIL)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Sitemap/Item,JK}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Form\Type\JQueryUploadType:
        class: App\Form\Type\JQueryUploadType
        arguments:
            - '@oneup_uploader.templating.uploader_helper'
