parameters:
    locale: 'fr'
    google_analytics_id: '%env(GOOGLE_ANALYTICS_ID)%'
    hotjar_enabled: '%env(HOTJAR_ENABLED)%'
    delivery_address: '%env(DELIVERY_ADDRESS)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    google_scope: '%env(GOOGLE_SCOPE)%'
    google_allowed_users: '%env(GOOGLE_ALLOWED_USERS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $googleAllowedUser: '%google_allowed_users%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


