services:
    app_partner_repository:
        class: AppBundle\Repository\PartnerRepository
        factory:
            - '@doctrine'
            - getRepository
        arguments:
            - AppBundle\Entity\Partner
