services:
    cms.module.article:
        class: JK\CmsBundle\Module\Article\ArticleModule
        arguments:
            - '@cms.article.repository'
        tags:
            - {name: 'cms.module'}

    cms.module.search:
        class: JK\CmsBundle\Module\SearchModule
        arguments:
            - '@form.factory'
        tags:
            - {name: 'cms.module'}
