services:
    cms.media.media_repository:
        class: App\Repository\MediaRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Media

    cms.article.repository:
        class: App\Repository\ArticleRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - App\Entity\Article

    cms.module.repository:
        class: App\Repository\ModuleRepository
