services:
    cms.media.media_upload_transformer:
        class: JK\CmsBundle\Form\Transformer\MediaUploadTransformer
        arguments:
            - '@cms.media.media_repository'

    cms.media.media_transformer:
        class: JK\CmsBundle\Form\Transformer\MediaTransformer
        arguments:
            - '@cms.assets.helper'

    cms.tag.collection_transformer:
        class: JK\CmsBundle\Form\Transformer\TagCollectionTransformer
        arguments:
            - '@jk.cms.tag_repository'
