parameters:

services:
    # Form Type
    bluebear.cms.content_type:
        class: 'BlueBear\CmsBundle\Form\Type\ContentType'
        tags:
            - {name: form.type, alias: content}
        calls:
            - [setContentTypeFactory, ['@bluebear.cms.content_type_factory']]

    bluebear.cms.category_type:
        class: 'BlueBear\CmsBundle\Form\Type\CategoryType'
        arguments:
            - '@cms.media.media_transformer'
        tags:
            - {name: form.type, alias: category}

    bluebear.cms.parameters:
        class: 'BlueBear\CmsBundle\Form\Type\ParametersType'
        tags:
            - {name: form.type, alias: parameters}

    cms.article.form:
        class: 'BlueBear\CmsBundle\Form\Type\ArticleType'
        arguments:
            - '@cms.media.media_transformer'
        tags:
            - {name: form.type, alias: article}

    bluebear.cms.comment_type:
        class: 'BlueBear\CmsBundle\Form\Type\CommentType'
        tags:
            - {name: form.type, alias: comment}

    cms.form.page_type:
        class: 'BlueBear\CmsBundle\Form\Type\PageType'
        tags:
            - {name: form.type, alias: page}
        arguments:
            - '@cms.form.helper'

    bluebear.cms.import_type:
        class: 'BlueBear\CmsBundle\Form\Type\ImportType'
        tags:
            - {name: form.type, alias: import}

    # Form Helper
    cms.form.helper:
        class: JK\CmsBundle\Form\Helper\FormHelper
