services:
    lag.cms.comment_repository:
        class: BlueBear\CmsBundle\Repository\CommentRepository
        tags:
            - {name: doctrine.repository}

    lag.cms.article_repository:
        class: BlueBear\CmsBundle\Repository\ArticleRepository
        tags:
            - {name: doctrine.repository}

    lag.cms.category_repository:
        class: BlueBear\CmsBundle\Repository\CategoryRepository
        tags:
            - {name: doctrine.repository}

#    lag.cms.user_repository:
#        class: BlueBear\CmsBundle\Repository\UserRepository
#        tags:
#            - {name: doctrine.repository}
    lag.cms.user_repository:
        class: BlueBear\CmsBundle\Repository\UserRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\User
