services:
    jk.cms.comment_repository:
        class: BlueBear\CmsBundle\Repository\CommentRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\Comment

    jk.cms.category_repository:
        class: BlueBear\CmsBundle\Repository\CategoryRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\Category

    jk.cms.user_repository:
        class: BlueBear\CmsBundle\Repository\UserRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\User

    jk.cms.tag_repository:
        class: BlueBear\CmsBundle\Repository\TagRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\Tag

    jk.cms.import_repository:
        class: BlueBear\CmsBundle\Repository\ImportRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\Import

    jk.cms.page_repository:
        class: BlueBear\CmsBundle\Repository\PageRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - BlueBear\CmsBundle\Entity\Page
