# Guard
#login:
#    path: /login
#    defaults: {_controller: 'BlueBearCmsBundle:Guard:login'}
#
#login_check:
#    path: /login_check
#    defaults: {_controller: 'BlueBearCmsBundle:Guard:loginCheck'}
#
logout:
    path: /logout

# Cms
#bluebear.cms.homepage:
#    path: /
#    defaults: {_controller: 'JKCmsBundle:Dashboard:dashboard'}

bluebear.cms.article.preview:
    path: /article/preview/{id}
    defaults: {_controller: 'BlueBearCmsBundle:Article:preview'}

# Image
cms.image.gallery_dialog:
    path: /images/gallery/dialog
    defaults: {_controller: 'BlueBearCmsBundle:Image:galleryDialog'}
