# Contents
bluebear.cms.content.list:
    path: /content/list/{name}
    defaults: {_controller: BlueBearCmsBundle:Backoffice:listContent}

bluebear.cms.content.add:
    path: /content/add/{name}
    defaults: {_controller: BlueBearCmsBundle:Backoffice:listContent}