# Guard
login:
    path: /login
    defaults: {_controller: BlueBearCmsBundle:Guard:login}

login_check:
    path: /login_check
    defaults: {_controller: BlueBearCmsBundle:Guard:loginCheck}

logout:
    path: /logout

# Cms
bluebear.cms.homepage:
    path: /
    defaults: {_controller: BlueBearCmsBundle:Cms:homepage}

bluebear.cms.dashboard:
    path: /dashboard
    defaults: {_controller: BlueBearCmsBundle:Cms:dashboard}

bluebear.cms.article.preview:
    path: /article/preview
    defaults: {_controller: BlueBearCmsBundle:Article:preview}
