# Contents
bluebear.cms.content.list:
    path: /content/list/{type}
    defaults: {_controller: BlueBearCmsBundle:Content:list}

bluebear.cms.content.add:
    path: /content/add/{type}
    defaults: {_controller: BlueBearCmsBundle:Content:edit}