parameters:
    # Factories
    bluebear.cms.content_type_factory.class: BlueBear\CmsBundle\Factory\ContentTypeFactory
    # Subscribers
    bluebear.cms.kernel_subscriber.class: BlueBear\CmsBundle\Event\Subscriber\KernelSubscriber
    # Form Type
    bluebear.cms.content_type.class: BlueBear\CmsBundle\Form\ContentType
    bluebear.cms.category_type.class: BlueBear\CmsBundle\Form\CategoryType
    # Managers
    bluebear.cms.manager.content.class: BlueBear\CmsBundle\Manager\ContentManager
services:
    # Factories
    bluebear.cms.content_type_factory:
        class: %bluebear.cms.content_type_factory.class%

    # Subscribers
    bluebear.cms.kernel_subscriber:
        class: %bluebear.cms.kernel_subscriber.class%
        arguments: [@twig, @bluebear.cms.content_type_factory, %bluebear.cms.content%]
        tags:
            - {name: kernel.event_subscriber}

    # Form Type
    bluebear.cms.content_type:
        class: %bluebear.cms.content_type.class%
        tags:
            - {name: form.type, alias: content}
        calls:
            - [setContentTypeFactory, [@bluebear.cms.content_type_factory]]
    bluebear.cms.category_type:
        class: %bluebear.cms.category_type.class%
        tags:
            - {name: form.type, alias: category}

    # Managers
    bluebear.cms.manager.content:
        class: %bluebear.cms.manager.content.class%
        calls:
            - [setContainer, [@service_container]]
