imports:
    - { resource: forms.yml }
    - { resource: repositories.yml }

parameters:
    # Factories
    bluebear.cms.content_type_factory.class: BlueBear\CmsBundle\Factory\ContentTypeFactory
    bluebear.cms.dashboard_factory: BlueBear\CmsBundle\Dashboard\Factory\DashboardFactory
    # Subscribers
    bluebear.cms.kernel_subscriber.class: BlueBear\CmsBundle\Event\Subscriber\KernelSubscriber
    # Managers
    bluebear.cms.manager.content.class: BlueBear\CmsBundle\Manager\ContentManager
    # Finders
    bluebear.cms.article_finder.class: BlueBear\CmsBundle\Finder\ArticleFinder
    # Assetic
    lag.assetic.bundler_compass_filter.class: BlueBear\CmsBundle\Assetic\Filter\BundlerCompassFilter
services:
    # Factories
    bluebear.cms.content_type_factory:
        class: %bluebear.cms.content_type_factory.class%

    bluebear.cms.dashboard_factory:
        class: %bluebear.cms.dashboard_factory%
        arguments:
            - '@jk.cms.comment_repository'
            - '@jk.cms.article_repository'

    # Subscribers
    bluebear.cms.kernel_subscriber:
        class: %bluebear.cms.kernel_subscriber.class%
        arguments: ['@twig', '@bluebear.cms.content_type_factory', %bluebear.cms.content%]
        tags:
            - {name: kernel.event_subscriber}

    # Managers
    bluebear.cms.manager.content:
        class: %bluebear.cms.manager.content.class%
        calls:
            - [setContainer, ['@service_container']]

    # Finders
    bluebear.cms.article_finder:
        class: %bluebear.cms.article_finder.class%
        arguments: ['@jk.cms.article_repository']



    lag.assetic.bundler_compass_filter:
        class: BlueBear\CmsBundle\Assetic\Filter\BundlerCompassFilter
        tags:
            - {name: assetic.filter, alias: bundler}
        arguments: [%kernel.root_dir%, %kernel.cache_dir%]

    # importer
    bluebear.cms.import.wordpress_importer:
        class: BlueBear\CmsBundle\Import\Importer\WordPressImporter
        arguments:
            - '@logger'
            - '@jk.cms.category_repository'
            - '@jk.cms.user_repository'
            - '@jk.cms.article_repository'
            - '@jk.cms.tag_repository'
            - '@jk.cms.comment_repository'
            - '@jk.cms.import_repository'

    # factory:
    bluebear.cms.import.importer_factory:
        class: BlueBear\CmsBundle\Import\Factory\ImporterFactory
        calls:
            - [setContainer, ['@service_container']]
