parameters:
    # factories
    bluebear.cms.content_type_factory.class: BlueBear\CmsBundle\Cms\Factory\ContentTypeFactory
    # subscribers
    bluebear.cms.kernel_subscriber.class: BlueBear\CmsBundle\Event\Subscriber\KernelSubscriber
services:
    bluebear.cms.content_type_factory:
        class: %bluebear.cms.content_type_factory.class%

    bluebear.cms.kernel_subscriber:
        class: %bluebear.cms.kernel_subscriber.class%
        arguments: [@twig, @bluebear.cms.content_type_factory, %bluebear.cms.content%]
        tags:
            - {name: kernel.event_subscriber}