imports:
    - { resource: forms.yml }

parameters:
    # Factories
    bluebear.cms.content_type_factory.class: BlueBear\CmsBundle\Factory\ContentTypeFactory
    # Subscribers
    bluebear.cms.kernel_subscriber.class: BlueBear\CmsBundle\Event\Subscriber\KernelSubscriber
    # Managers
    bluebear.cms.manager.content.class: BlueBear\CmsBundle\Manager\ContentManager
    # Finders
    bluebear.cms.article_finder.class: BlueBear\CmsBundle\Finder\ArticleFinder
services:
    # Factories
    bluebear.cms.content_type_factory:
        class: %bluebear.cms.content_type_factory.class%

    # Subscribers
    bluebear.cms.kernel_subscriber:
        class: %bluebear.cms.kernel_subscriber.class%
        arguments: [@twig, @bluebear.cms.content_type_factory, %bluebear.cms.content%]
        tags:
            - {name: kernel.event_subscriber}

    # Managers
    bluebear.cms.manager.content:
        class: %bluebear.cms.manager.content.class%
        calls:
            - [setContainer, [@service_container]]

    # Finders
    bluebear.cms.article_finder:
        class: %bluebear.cms.article_finder.class%
        arguments: [@bluebear.cms.repository.article]

    # Article repository
    bluebear.cms.repository.article:
        class: BlueBear\CmsBundle\Repository\ArticleRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['BlueBearCmsBundle:Article']
