parameters:
    # factories
    bluebear.cms.content_type_factory.class: BlueBear\CmsBundle\Factory\ContentTypeFactory
    # subscribers
    bluebear.cms.kernel_subscriber.class: BlueBear\CmsBundle\Event\Subscriber\KernelSubscriber
    # form
    bluebear.cms.content_type.class: BlueBear\CmsBundle\Form\ContentType
    # managers
    bluebear.cms.manager.content.class: BlueBear\CmsBundle\Manager\ContentManager
services:
    bluebear.cms.content_type_factory:
        class: %bluebear.cms.content_type_factory.class%

    bluebear.cms.kernel_subscriber:
        class: %bluebear.cms.kernel_subscriber.class%
        arguments: [@twig, @bluebear.cms.content_type_factory, %bluebear.cms.content%]
        tags:
            - {name: kernel.event_subscriber}

    bluebear.cms.content_type:
        class: %bluebear.cms.content_type.class%
        tags:
            - {name: form.type, alias: content}
        calls:
            - [setContentTypeFactory, [@bluebear.cms.content_type_factory]]

    bluebear.cms.manager.content:
        class: %bluebear.cms.manager.content.class%
        calls:
            - [setContainer, [@service_container]]