parameters:
    # Factories
    bluebear.cms.content_type_factory.class: BlueBear\CmsBundle\Factory\ContentTypeFactory
    # Subscribers
    bluebear.cms.kernel_subscriber.class: BlueBear\CmsBundle\Event\Subscriber\KernelSubscriber
    # Form Type
    bluebear.cms.content_type.class: BlueBear\CmsBundle\Form\Type\ContentType
    bluebear.cms.category_type.class: BlueBear\CmsBundle\Form\Type\CategoryType
    bluebear.cms.parameters_type.class: BlueBear\CmsBundle\Form\Type\ParametersType
    bluebear.cms.article_type.class: BlueBear\CmsBundle\Form\Type\ArticleType
    bluebear.cms.comment_type.class: BlueBear\CmsBundle\Form\Type\CommentType
    # Managers
    bluebear.cms.manager.content.class: BlueBear\CmsBundle\Manager\ContentManager
    # Finders
    bluebear.cms.article_finder.class: BlueBear\CmsBundle\Service\ArticleFinder
services:
    # Factories
    bluebear.cms.content_type_factory:
        class: %bluebear.cms.content_type_factory.class%

    # Subscribers
    bluebear.cms.kernel_subscriber:
        class: %bluebear.cms.kernel_subscriber.class%
        arguments: [@twig, @bluebear.cms.content_type_factory, %bluebear.cms.content%]
        tags:
            - {name: kernel.event_subscriber}

    # Form Type
    bluebear.cms.content_type:
        class: %bluebear.cms.content_type.class%
        tags:
            - {name: form.type, alias: content}
        calls:
            - [setContentTypeFactory, [@bluebear.cms.content_type_factory]]

    bluebear.cms.category_type:
        class: %bluebear.cms.category_type.class%
        tags:
            - {name: form.type, alias: category}

    bluebear.cms.parameters:
        class: %bluebear.cms.parameters_type.class%
        tags:
            - {name: form.type, alias: parameters}

    bluebear.cms.article_type:
        class: %bluebear.cms.article_type.class%
        tags:
            - {name: form.type, alias: article}

    bluebear.cms.comment_type:
        class: %bluebear.cms.comment_type.class%
        tags:
            - {name: form.type, alias: comment}

    # Managers
    bluebear.cms.manager.content:
        class: %bluebear.cms.manager.content.class%
        calls:
            - [setContainer, [@service_container]]

    # Finders
    bluebear.cms.article_finder:
        class: %bluebear.cms.article_finder.class%
